import { Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Aditya Gupta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fira_code.className}>
        <div className="flex flex-col h-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
